### ISSUE TITLE
Error saving model

### ISSUE THREAD

**Issue by kg6kvq** [barissayil/SentimentAnalysis#1]
When I run train.py the following error occurs:

Epoch 0 complete! Validation Accuracy : 0.8917410969734192, Validation Loss : 0.27176217176020145
Best validation accuracy improved from 0 to 0.8917410969734192, saving model...
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    train(net, criterion, optimizer, train_loader, val_loader, args)
  File "train.py", line 77, in train
    torch.save(net.state_dict(), 'models/model'.format(ep, args.freeze_bert))
NameError: name 'ep' is not defined

**Comment by barissayil** [comment]
Thanks for notifying me, it's fixed now.
