### ISSUE TITLE
I cant install the repository as a site-package and use it.

### ISSUE THREAD

**Issue by Roiinbarr** [barissayil/SentimentAnalysis#11]
Hey barissayil, 

Can you please include in the repository a setup.py file ? I cant use pip to install it as a package.

Thanks,
Roi.

**Comment by barissayil** [comment]
Hi,

I didn't turn this repo into a python package so this is why you can't use pip to install it. You should use git clone to install it then follow the instructions.

I can also turn it into a python package if there's interest.
