### ISSUE TITLE
"string indices must be integers" error

### ISSUE THREAD

**Issue by litingzhou1** [barissayil/SentimentAnalysis#15]
Hi @barissayil,

Thanks you for sharing your excellent work. I met an error of "string indices must be integers"  When I run the analyze.py file. The error is showed below:
 ```
The error are list below:
Please wait while the analyser is being prepared.
Input sentiment to analyze: I am happy.
Traceback (most recent call last):
  File "analyze.py", line 53, in <module>
    classify_sentiment(sentence)
  File "analyze.py", line 14, in classify_sentiment
    logit = model(input_ids=input_ids, attention_mask=attention_mask)
  File "/Users/insight/opt/anaconda3/envs/meetingminutes-sentiment/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/insight/Projects/MeetingMinutes-Minning/bert-extractive-summarizer/sentiment/SentimentAnalysis/modeling.py", line 23, in forward
    cls_reps = reps[:, 0]
TypeError: string indices must be integers
```
Could you please give me some suggestion to find the solution? Thanks a lot!

**Comment by litingzhou1** [comment]
I found a useful comment:

To fix string indices error change these lines in the BertEmotionClassifier class.

change

`self.bert = BertModel(config) `
to
`self.bert = BertModel.from_pretrained('bert-base-uncased')`

change

`reps, _ = self.bert(input_ids=input_ids, attention_mask=attention_mask) `
to
`reps = self.bert(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state`

**Comment by barissayil** [comment]
Thanks for letting me know, one of the updates to HuggingFace had broken the code but I fixed it now.
