### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'last_hidden_state'

### ISSUE THREAD

**Issue by wenk207** [barissayil/SentimentAnalysis#24]
Hey, thanks for the code.

When I was running, there was some error. Could you please help me to check it. Thank

`  File "F:\PycharmProjects\SentimentAnalysis-master\modeling.py", line 25, in forward
    cls_reps = outputs.last_hidden_state[:, 0]
AttributeError: 'tuple' object has no attribute 'last_hidden_state'
`

**Comment by barissayil** [comment]
Hi, I just released a new version with much clearer instructions. The commands listed should 100% work.
