### ISSUE TITLE
three classifications?

### ISSUE THREAD

**Issue by dongzhenguo2016** [barissayil/SentimentAnalysis#29]
Can you achieve three classifications?positive、negative and neutral

**Comment by lonycc** [comment]
@dongzhenguo2016 just assert neutral when the value of torch.sigmoid(logit.unsqueeze(-1)).item() is between 0.4 and 0.6

**Comment by barissayil** [comment]
Currently the only way to do what you want is to do as @lonycc said, but the results won't be too good as the current data is only classified as positive and negative.  But you can change the code a little and use a different dataset which also has neutral sentiments.
