### ISSUE TITLE
Japanese Sentiment Analysis

### ISSUE THREAD

**Issue by msmmpts** [barissayil/SentimentAnalysis#30]
Can I use this model for direct inference on japanese text  or is re-training necessary ?

**Comment by barissayil** [comment]
Hi, you can use set `--model_name_or_path` argument to `bert-base-japanese` and it should work but you will need to use a Japanese dataset. So you need to delete the files in `./data` and add Japanese sentiment data. Otherwise the code should need very few changes.

**Comment by msmmpts** [comment]
Thanks for the response.

Another follow up question, suppose I had to train using 3 classes, (Positive, Negative, Neutral) what all code changes are required?
