### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by dorumpir** [barissayil/SentimentAnalysis#31]
Hi, when I uncommented the choosing device part and tried to execute the analize.py, I received runtime error, it seems some of the tensors are still on cpu.
	# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
	# model = model.to(device)
"
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
"
So do you know how to solve this?

**Comment by barissayil** [comment]
Hi, I just released a new version which fixes this.
