### ISSUE TITLE
cannot import name 'AlbertPreTrainedModel' from 'transformers'

### ISSUE THREAD

**Issue by MM-GA** [barissayil/SentimentAnalysis#8]
My (limited) understanding is that in the transfomers code some pretrained models have  renamed or moved. https://github.com/huggingface/transformers/pull/4636

**Comment by barissayil** [comment]
Which command are you trying to run?
Just now I tried `python train.py --model_name_or_path albert-base-v2` with the latest version of transformers (3.1.0) and there was no import error.

**Comment by sagarraina1997** [comment]
Where have you used SST? I only see a Class made by you named SST in Data.py file.
